# Generated by Django 4.2.5 on 2024-05-20 15:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0004_alter_obra_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('reporteId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=200)),
                ('fotos', models.CharField(max_length=255)),
                ('audios', models.CharField(max_length=255)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('tareaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obra.tarea')),
            ],
        ),
    ]
