# Generated by Django 4.2.5 on 2024-06-04 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0006_obra_obra_delete_obra_obra_status_tarea_tarea_delete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='tarea_status',
        ),
    ]
